name: Dependency review for pull requests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v5
  
  dependency-review:
    runs-on: ubuntu-slim
    needs: dependency-submission
    if: github.event_name == 'pull_request'
    steps:
      - name: Perform dependency review
        uses: actions/dependency-review-action@v4
